os: linux
language: bash

services:
  - docker

before_install:
  # build docker image
  - docker build -t pivotal .
  # install goss
  - curl -L https://goss.rocks/install | sudo sh

script:
  - ./test.sh