os: linux
language: bash
services:
- docker
before_install:
- docker build -t pivotal .
- curl -L https://goss.rocks/install | sudo sh
script:
- "./test.sh"
notifications:
  slack:
    secure: n9Y6UwK0PJeSud6tYhEu1YbITJy2+uysyFpPLJ/A/Kw2NpOeKP6/d0Ocid4XaW503ng08UrjBlRqAmf980iR0si8f5bIfJB7g6fwGiTt0g3fCG3fC8Oksu88YNObeaBH0rDSEktpZMMD2oYR/UK3iWxVxqHNWw9SUQDlQ17GjGZJl27ls6HtsrdTXGj4ST7IwBmXf1PhAjLvEA413p1T2FLROLypnqNcgC+uFFFgMHxgSGBTa/64sLo+8lUY3AQ/jGOcgR27CUpnT60auwL9aa74DR54mUxnN8+Z7jRB4Aom/J3bliWUFErrbas6VgP5OI8OKKIxemU3Lf4X04A5aoedqf5lf7PhRkPHzx0ABT6tyYb8lPRTPfozsgNzXrIuWFJ2gWZWvQX8+x+buFAw8S3cNVk2Ey9z+g45jxQwt73DwZJUvcg72CKGww7XhR17zRzFPEaoPUi61Shu5LBrtaNABuuz7pzl94Wm3KS1j9cX1SLl2Qn3J8Akfwipw1wtVjsD8E5lVabuIqabYa18yDGuXKcasz4PDfnBb1031lFWIgtpZ8GxJoZCCaIu75KtejamTPp2ZIExcvJ4vWuezinAmBcEFjVkpCdNE7QxnyJzH11UGAzEh6AuzONZGuseaXA4EPe46Kr4Q9lPFIpfyZ5BVTo3Bxw1dzyM6mbQS4w=
    rooms:
      secure: UunuzIN7505D9Dji/29hN3RvGpE4ZTCsZrD9hktykt7+S7mKv99XPevw8J7QQpcC2RUHy+l4rQCLV6lKeC+gmAapuFAefodNpqL5v9ligmq1kHvbmBHel6vxfaoSU0saQW0WXATBxn33A5E6GKxklUpqcxIChB0umTMpZY3qKxvQCgGxbrWbH/f8pi/wqLoBtqDRow1zZIacKYRc460JB1ekPS2S1yQHPjA5WmTYuT4So3eclsDx4HjXL9/RoY/Wg5h4fP1WdDvqUuxYVUp/UU7X3F+cnRcv+bmS48T2z8l0ItwzZRG0imp/1ZLlggWMGZqHLDr5yiJTNZ3Tll09b9H4ldQAPLdXkOpYoYk4g8egc8tLFM2LV7rqpzG2H+Cm3m5XCtJlM5bXVhlTyFU2JE7iudqXbUf+LMhLHzPbNMNNszbQShep3ipHlnV6WYGY1cM0DnKf1JgM9icmEtxvhITu2+kHvsZ6I4KpMXeZQN9GCq6PG00sN/AGLOCJv0Jmxa1sYzjn+NQtpDZ79sXu3/ZSS3U0i3XtwE+If8p3xG6lpRh5qdV0vOaHRikQgwCEQpkX1yFggSwkEOK5o5OdobmQ6qbp9984JnrbvwKdNx503x5LHwcAWFpKXWTxfK4914tH3wx3CqfdCiKESlU8kM2lVrFGjxS1w4UZ4OspbL4=
