os: linux

language: bash

services:
- docker

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

before_install:
- docker build -t pivotal .
- curl -L https://goss.rocks/install | sudo sh

script:
- dgoss run pivotal sleep 3

after_success:
- ./docker.sh
