os: linux
language: bash
services:
- docker
before_install:
- docker build -t pivotal .
- curl -L https://goss.rocks/install | sudo sh
script:
- "./test.sh"
notifications:
  slack:
    rooms:
      secure: 4Y0GwP3DednYxzRTH3nenGAi9FvK0rAmM9khCOyFozrcJPLpKUb9jOhlXGyvq9kO7PewfdxBzc1+M50RZ2BP+VWoSaIuI6zRx8A6sAfkh6xvL/mW1QF+yjkwrEJf8hgIOCzrbbY2zWpUg1F9gSUvjzAHGgpiLI37pyJ9sA52W1xIwxrimzoE79JWtdg/uSDbEa8c46gjU9SHQ/dmCBs7Grv/ubd5ZJMGOjk410fCPxs7/wQzhrCGSPbIoeo1XOsZa9JYirDLoa7rG7JQmYsyhkXOMz/BybY+xl6ijjLdH3lhZMtR2h7AfJYRvhdD5zGEt32sE5uQqwX0vOJcGvmL6tyIrhT9t8pW6DaUFk0xRM4DbVkhdrrKhe5TtXOquaPeumUI0xA0kpeMSqGvJxqP6ImhiPQLxkLwQjrXAjRyhf0v0XUG7j8qx5Ffi6VLEgzZ4Wc5mkBW+vaILpmWqhkvnBCZRKL3S2S1MKBNCAsrMw8GDtg0eIBaHrtkceF4n390P/ex+YbRJ9QZOwIaWkMNT0DEwO7v7VV6u2cboZi8oWRx3gj8tXv56Y16QaeAqa97gDqyugK0M5Z5xeyBwZtNgHqXSnknrLYWAZxJJ4PpKIQ/ZO+6w1DwG845q92/AToQzduVbtC0qMgCeUXNSCfTeV815o/Vl6gVNKEi6xrQxQs=
